train_lr: C:/Users/o/Desktop/Python_project/UW_MobileGAN/data/train/LR
train_hr: C:/Users/o/Desktop/Python_project/UW_MobileGAN/data/train/HR
val_lr:   C:/Users/o/Desktop/Python_project/UW_MobileGAN/data/val/LR
val_hr:   C:/Users/o/Desktop/Python_project/UW_MobileGAN/data/val/HR

img_size: 256

epochs: 50
batch_size: 8
lr: 2.0e-4
seed: 42

lambda_l1: 10.0
lambda_lpips: 0.5
lambda_adv: 1.0
lambda_feat: 0.2
lambda_edge: 0.0
feat_alpha: 0.7

use_dynamic_weighting: false

out_dir: C:/Users/o/Desktop/Python_project/UW_MobileGAN/outputs_journal/feat_only
save_interval: 5

generator_type: mobile

euvp_lr: C:/Users/o/Desktop/Python_project/UW_MobileGAN/data/EUVP/underwater_dark/trainA
euvp_hr: C:/Users/o/Desktop/Python_project/UW_MobileGAN/data/EUVP/underwater_dark/trainB