# ========================
# MobileGAN (Wendy版配置)
# ========================

# ========= UIEB 主训练/验证 =========
train_lr: C:/Users/o/Desktop/Python_project/UW_MobileGAN/data/train/LR
train_hr: C:/Users/o/Desktop/Python_project/UW_MobileGAN/data/train/HR
val_lr:   C:/Users/o/Desktop/Python_project/UW_MobileGAN/data/val/LR
val_hr:   C:/Users/o/Desktop/Python_project/UW_MobileGAN/data/val/HR

img_size: 256

# ========= 训练设置 =========
epochs: 50
batch_size: 8
lr: 2.0e-4
seed: 42

# ========= 原有损失权重 =========
lambda_l1: 10.0
lambda_lpips: 0.5
lambda_adv: 1.0
lambda_feat: 0.2

# ========= 新增：期刊版改进参数 =========
lambda_edge: 0.1
feat_alpha: 0.7

# ========= 输出 =========
out_dir: C:/Users/o/Desktop/Python_project/UW_MobileGAN/outputs_journal/full_revised
save_interval: 5

# ========= 生成器类型 =========
# mobile: 你的轻量化 MobileGAN
# funie : FUnIE-GAN baseline
generator_type: funie

# ========= EUVP 外部泛化测试（先写好，后面 test 脚本会用） =========
euvp_lr: C:/Users/o/Desktop/Python_project/UW_MobileGAN/data/EUVP/underwater_dark/trainA
euvp_hr: C:/Users/o/Desktop/Python_project/UW_MobileGAN/data/EUVP/underwater_dark/trainB